version: '3.8'
services:
   sqlserver:
     image: mcr.microsoft.com/mssql/server:2019-latest
     platform: linux/amd64 
     container_name: sqlserver
     environment:
       - ACCEPT_EULA=Y
       - SA_PASSWORD=DevOpsDB#Nov25
     ports:
       - "1433:1433"
     volumes:
       - sqlserver-data:/var/opt/mssql

   steadtlerhr-api:
    image: shoebimtiaz/steadtlerhr:latest
    container_name: steadtlerhr-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EmployeeDB;User Id=sa;Password=DevOpsDB#Nov25;

volumes:
  sqlserver-data:

